---
- name: 'Configure plugins repository'
  yum_repository:
    name: "foreman-plugins-{{ foreman_scap_client_release }}"
    description: "Foreman plugins repository"
    baseurl: "{{ foreman_scap_client_repo_url }}"
    gpgcheck: "{{ foreman_scap_client_repo_gpg }}"
    gpgkey: "{{ foreman_scap_client_repo_key }}"
    state: "{{ foreman_scap_client_repo_state }}"

- name: 'Install the foreman_scap_client package'
  yum:
    name: "rubygem-foreman_scap_client"
    state: "{{ foreman_scap_client_state }}"

- name: 'Get cert paths from subscription-manager'
  script: foreman_scap_client_facts.rb
  register: facts_output

- name: 'Set facts for foreman_scap_client'
  set_fact:
    facts_json: "{{ facts_output.stdout }}"

- debug:
    msg: "Penene"

- name: 'Create facts dir'
  path: /etc/ansible/facts.d
  state: directory

- name: 'Create custom facts file'
  template:
    src: foreman_scap_client.fact.j2
    dest: /etc/ansible/facts.d
    owner: root

- name: 'Create cron in /etc/cron.d/'
  template:
    src: "{{ foreman_scap_client_cron_template }}"
    dest: /etc/cron.d/foreman_scap_client_cron
    owner: root

- name: 'Create config.yaml in /etc/foreman_scap_client'
  template:
    src: templates/config.yaml.j2
    dest: /etc/foreman_scap_client/config.yaml
    owner: root

- name: "Ensure cron and config are {{ foreman_scap_client_state }}"
  file:
    path: "{{ item }}"
    state: "{{ 'absent' if foreman_scap_client_state == 'absent' else 'file' }}"
  with_items:
    - /etc/cron.d/foreman_scap_client_cron
    - /etc/foreman_scap_client/config.yaml
